public enum EventKey
{
    NONE = -1,
    STARTGAME,
    ENDGAME,
    UPDATE_UI,
    ONUSEMANA,
    ONREGETMANA,
    ONBREAKBUBBLE,
    ONBREAKBUBBLEABLE,
    StopPlaying,
    ONCLICKBUTTON,
    ResumePlaying,
    ONUSEMANAFORDASH,
    ONBREAKBUBBLE2,
}